package core

import (
	"fmt"
	"strings"
)

func GenerateSSHConfig(hosts []Host) string {
	var sb strings.Builder

	sb.WriteString("# Generated by Hostbook. Do not edit manually.\n\n")

	for _, host := range hosts {
		sb.WriteString(fmt.Sprintf("Host %s\n", host.Name))
		sb.WriteString(fmt.Sprintf("    Hostname %s\n", host.Hostname))
		sb.WriteString(fmt.Sprintf("    User %s\n", host.User))
		if host.Port != "" {
			sb.WriteString(fmt.Sprintf("    Port %s\n", host.Port))
		}
		if host.IdentityFile != "" {
			sb.WriteString(fmt.Sprintf("    IdentityFile %s\n", host.IdentityFile))
		}
		sb.WriteString("\n")
	}

	return sb.String()
}
